create table "user"
(
    user_id   bigint generated by default as identity,
    password  varchar(255),
    user_name varchar(255),
    primary key (user_id)
);
create table amount_type
(
    amount_type_id bigint not null,
    user_id        bigint not null,
    type_name      varchar(255),
    primary key (amount_type_id, user_id)
);
create table category
(
    category_id   bigint not null,
    user_id       bigint not null,
    category_name varchar(255),
    primary key (category_id, user_id)
);
create table shopping_item
(
    amount              float(53),
    bought              boolean,
    moved_to_bought     boolean,
    amount_type_user_id bigint not null,
    category_user_id    bigint not null,
    item_amount_type_id bigint not null,
    item_category_id    bigint not null,
    shopping_item_id    bigint not null,
    user_id             bigint not null,
    item_name           varchar(255),
    primary key (item_amount_type_id, item_category_id, shopping_item_id, user_id)
);
alter table if exists amount_type
    add constraint FKeff3ohc75y0abdg26xufkkt76 foreign key (user_id) references "user";
alter table if exists category
    add constraint FKqikjh4wi1ygrf1xvbsx21ax86 foreign key (user_id) references "user";
alter table if exists shopping_item
    add constraint FKlwoqjnsk8eo804b2ysjbcif5k foreign key (user_id) references "user";
alter table if exists shopping_item
    add constraint FK4qsoykac4h3cwpyytd3c4qb80 foreign key (item_amount_type_id, amount_type_user_id) references amount_type;
alter table if exists shopping_item
    add constraint FKta2lunw80rvbxayo3oxhaatbw foreign key (item_category_id, category_user_id) references category;
